name: Package CI


on:
  push:
    paths:
      - ".github/workflows/package.yml"
      - "deps.edn"
      - 'build/package.clj'
      - "src/core/**/*.clj"
      - "src/core/**/*.cljc"
      - "src/test/**/*.clj"
      - "src/test/**/*.cljc"
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  java-version: '17'
  clojure-cli: latest
  library: io.github.ajchemist/kakao.login


jobs:
  test:
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "17" ]
        clojure: [ "1.11" ]
    name: test @ JDK = ${{ matrix.java }} CLJ = ${{ matrix.clojure }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}


      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: ${{ env.clojure-cli }}


      - name: Test runner
        env:
          TESTOPT: "-X:provided:test:test-runner"
        run: |
          clojure $TESTOPT


  package:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      # This reset settings.xml
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.java-version }}


      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: ${{ env.clojure-cli }}


      - name: Preparation
        run: |
          cp .ci/settings.xml $HOME/.m2/
          mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-deploy-plugin:2.8


      - name: Make package
        run: |
          clojure -T:build jar :lib ${{ env.library }}

      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: mvn deploy:deploy-file -DpomFile="pom.xml" -Dfile="target/package.jar" -Dpackaging=jar -DrepositoryId="clojars" -Durl="https://clojars.org/repo"


      - name: Push a commit using the built-in token
        run: |
          git config --local user.name $GITHUB_ACTOR
          git config --local user.email $(git --no-pager show --format="<%ae>" -s HEAD)
          git add -- pom.xml
          git commit -m "$(clojure -X:build:maven-tool print-pom-version) [ci skip]"
          git remote -v
          git push
